title: <p align="center"> Berliana Spanic </p>

logo: "/images/FotoSpanic.png?raw=true"

description:
  <p align="center">
  <a href="pdf/CV [Berliana Spanic] 1.pdf">Resume</a> |
  <a href="pdf/Sertificate.pdf">Certificate</a> |
  <a href="https://www.linkedin.com/in/berlianaspanic/">LinkedIn</a> |
  <a href="https://github.com/berlianaspanic">GitHub</a>
  </p>
  
  <p align="justify">
  I am an undergraduate student at Diponegoro University in the Bachelor of Statistics study program. Interested in Data Science, especially Data Analytics and Data Scientist. 
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
