title: <p align="center"> Berliana Spanic </p>

logo: "/images/FotoSpanic.png?raw=true"

description:
  <p align="center">
  <a href="pdf/CV.pdf">Resume</a> |
  <a href="pdf/SERTIF.pdf">Certificate</a>
  <a href="https://www.linkedin.com/in/berlianaspanic/">LinkedIn</a> |
  <a href="https://github.com/berlianaspanic">GitHub</a>
  </p>
  
  <p align="justify">
  I am an Undergraduate Statistics Student at Diponegoro University who interested about Data Science and currently learning Python, SQL, and Looker Studio in Zenius and DQLab.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
